services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak-microservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
      - start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info,org.keycloak.authentication:trace,org.apache.http.wire:trace


